name: ApacheMQ CI

on:
  push:
    branches: [main]
    paths:
      - "apache-mq/**"
  pull_request:
    branches: [main]
    paths:
      - "apache-mq/**"

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      working-directory: ./apache-mq

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag poc-sgm-apachemq:$(date +%s)
        working-directory: ${{env.working-directory}}

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      working-directory: ./apache-mq

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{env.working-directory}}
          file: ./apache-mq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/poc-sgm-apachemq:latest
          

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
