name: SASCi CI

on:
  push:
    branches: [ main ]
    paths:
    - 'sasci/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'sasci/**'

jobs:

  build:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      working-directory: ./sasci

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ${{env.working-directory}}


  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/poc-sgm-sasci:latest
        working-directory: ${{env.working-directory}}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
      
      
